version: "v0.0.1"
env: "dev"
kafka:
  zookeeperconfigfile: "$HOME/kafka/config/zookeeper.properties"
  brokerconfigfile: "$HOME/kafka/config/server.properties"
mysql:
  username: "root"
  password: "password"
  hostport: "localhost:3306"
  dbname: ""
gcs:
  credentialfile: "config/xwork-dev-5e7544287095.json"